function ret = cspPacketCreaterFromDec( priority, sourceAddr, destAddr, destPort, sourcePort, payload )
%CSPPACKETCREATER Summary of this function goes here
%   Detailed explanation goes here
    ret = [];
    
    ret = [ret priority];
    
    ret = [ret...
        hexStrToBinArr(...
            dec2hex(...
                sourceAddr...
            )...
        )];
    
    ret = [ret...
        hexStrToBinArr(...
            dec2hex(...
                destAddr...
            )...
        ) ret];
    
    ret = [ret...
        hexStrToBinArr(...
            dec2hex(...
                destPort...
            )...
        )];
    
    ret = [ret...
        hexStrToBinArr(...
            dec2hex(...
                sourcePort...
            )...
        )];
    
    ret = [ret...
        hexStrToBinArr(...
            '00'...
        )];
    ret = [ret payload];
end

